spring.application.name=jobportal

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-orange-credit-adp85hy9-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

#spring.datasource.url=postgresql://ep-orange-credit-adp85hy9-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require


spring.datasource.username=neondb_owner
spring.datasource.password=npg_YjEA5wR9Vhob

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect